# [Pytorch basic document]

-----

pytorch를 활용하여 만들 수 있는 model은 무궁무진하지만 기초를 알지 못한다면 원하는 모델을 만들기는 쉽지 않다

해당 project에서는 pytorch의 기능과 함수들에 대해서 자세하게 보고 활용하여 활용 방법에 대해서 다루는 것을 목적으로 한다.

- Python Version : Python 3.13.7

참고 자료 : https://www.youtube.com/watch?v=kY14KfZQ1TI&list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1

참고자료 : https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html

-----

## 목차(contents)

- 1. Tensor (Tensor 생성, Tensor의 Attribution)
- 2. Tensor Operations
- 3. Tensor Math
- 4. Neural Network (make, train, evaluate(using test, new data), save & load model)
- 5. CNN(Convolution Neural Network) - Image fliter, Image kernel, Convolutional Layer & RGB, Pooling Layer, Train, Test, Checking Work

In [28]:
# pytorch install, numpy

%pip install --upgrade pip
%pip install torch
%pip install --upgrade torch
%pip install numpy
%pip install --upgrade numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [29]:
# pytorch 모델 import

import torch

# 1. Tensor란 무엇인가?
---

tensor(텐서)는 array나 matrix와 유사한 특수 자료구조로, pytorch에서는 tensor를 통해 model으로의 input과 output 뿐만 아닌 모델의 매개변수를 encoding하는 과정에 사용된다.

tensor는 numpy의 ndarray와 유사하지만, GPU나 연산 가속을 위한 특수 하드웨어에서 실행 가능하다는 점이 다르다.

---

### Tensor의 종류

|Dimension|tensor 종류|명칭|
|:---:|:---:|:---:|
|0 dimension tensor|zeroth-order-tenso|scalar|
|1 dimension tensor|First-order-tensor|vector|
|2 dimension tensor|Second-order-tensor|matrix|
|3 dimension tensor|Third-order-tensor|tensor|
|4 dimension tensor|Fourth-order-tensor|stack with 3 dimension tensor|
|5 dimension tensor|Fifth-order-tensor|expand side with 4 dimension tensor|
|...|...|...|

![tensor의 종류](./tensor.png)

참고자료 : https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html

참고자료 : https://www.youtube.com/watch?v=2yBEZzQu8dA&list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1&index=2

이미지 출처 : Pytorch로 시작하는 딥러닝 입문



## 1) Tensor 초기화 및 생성
---

tensor 생성 당시 자료형은 자동으로 유추하여 맞게 생성되기 때문에 따로 지정할 필요는 없다.

크게 tensor의 생성 방법으로는 4가지로 나뉜다.

1) data -> tensor
2) data -> numpy array -> tensor
3) original_tensor -> duplicate_tensor(attribute 유지 O)
4) original_tensor -> duplicate_tensor(attribute 유지 X)
5) data(zero, one, random) -> tensor

---

In [30]:
# tensor 생성 (data -> tensor)

data = [[1, 2],[3, 4]] # 데이터 배열 생성
x_data = torch.tensor(data) # data를 tensor로 변환

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [31]:
# tensor 생성 (data -> numpy array -> tensor)
import numpy as np

np_array = np.array(data) # numpy array 생성
x_np = torch.from_numpy(np_array) # numpy array -> tensor로 변환

print(x_np)

tensor([[1, 2],
        [3, 4]])


In [32]:
# tensor 생성 (다른 tensor -> 새로운 tensor)
# 속성의 유지여부에 따라 ones_like, rand_like를 나눠서 쓰는데 속성에는 tensor의 shape과 datatype이 해당된다.

tensor_ones = torch.ones_like(x_data) # 기존 tensor의 속성을 유지
tensor_rand = torch.rand_like(x_data, dtype=float) # 기존 tensor의 속성을 변경

print(f"Ones Tensor : \n {tensor_ones} \n")
print(f"Random Tensor : \n {tensor_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.8947, 0.5516],
        [0.7662, 0.3233]], dtype=torch.float64) 



In [71]:
# tensor 생성을 random(랜덤값) 또는 constant(상수값)을 활용하여 생성하는 방법

shape = (3, 5) #tensor의 차원을 column:3, row:5로 setting

rand_tensor = torch.rand(shape) #랜덤값으로 shape에 맞게 tensor를 생성
ones_tensor = torch.ones(shape) #모든 원소값은 1로 shape에 맞게 tensor 생성
zeros_tensor = torch.zeros(shape) #모든 원소값을 0으로 shape에 맞게 tensor 생성

# 각 tensor의 구조 및 원소의 상태를 print하여 확인
print(f"rand_tensor \n {rand_tensor} \n")
print(f"ones_tensor \n {ones_tensor} \n")
print(f"zeros_tensor \n {zeros_tensor} \n")

# numpy array를 기준으로 원소 값 초기화를 통해 tensor 생성도 가능함

# torch.ones_like(t) # t와 같은 사이즈의 1로 채워진 tensor를 출력
# torch.zeros_like(t) # 모든 값을 0으로 
# torch.ones(size=[]) # 1로 채워진 size 차원의 tensor를 출력
# torch.zeros(size=[]) # 0으로 채워진 size 차원의 tensor를 출력

rand_tensor 
 tensor([[0.2095, 0.3311, 0.6936, 0.6714, 0.6296],
        [0.3809, 0.3754, 0.3260, 0.3126, 0.8773],
        [0.1281, 0.8869, 0.2443, 0.2409, 0.5985]]) 

ones_tensor 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

zeros_tensor 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 



## 2) Tensor의 Attribute(속성)

---

tensor의 attribute(속성)은 tensor의 shape, datatype 및 store device location을 의미한다.

따라서, 각 tensor는 이런 attribute를 모두 가지고 있기 때문에 특정 tensor의 shape/dtype/device의 속성을 확인이 가능하다

추가적인 속성 확인인 size(), dim()의 경우에는 메소드(함수)이기 때문에 (괄호)를 뺴먹지 않도록 주의해야 함.

---

In [73]:
# tensor 랜덤값으로 생성

tensor_sample = torch.rand(2, 3) #랜덤 값을 활용하여 생성한 2x3 tensor

print(f"tensor_sample \n {tensor_sample} \n") #tensor_sample을 출력
print(f"Shape of tensor : {tensor_sample.shape}") #tensor_sample의 shape을 출력
print(f"Size of tensor : {tensor_sample.size()}") #tensor_sample의 size를 출력
print(f"Dimension of tensor : {tensor_sample.dim()}") #tensor_sample의 dimension을 출력
print(f"Datatype of tensor : {tensor_sample.dtype}") #tensor_sample의 데이터 타입을 출력
print(f"Device tensor is stored on : {tensor_sample.device}") #tensor_sample이 저장된 device의 location을 출력


tensor_sample 
 tensor([[0.5339, 0.0088, 0.1896],
        [0.4668, 0.3965, 0.6455]]) 

Shape of tensor : torch.Size([2, 3])
Size of tensor : torch.Size([2, 3])
Dimension of tensor : 2
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


# 2. Tensor Operation(텐서 연산)

---

선형대수 연산 기능, 수학적 계산, 인덱싱, 슬라이싱, 임의 샘플링 등 tensor 구조로 연산 기능을 지원하는 pytorch에는 다양한 함수가 존재한다.

가장 기본적인 Reshape, Slice 기법을 확인 후 수학적 tensor 연산인 Add, Subtract, Multiply, Divide, Remainders, Exponent, Shorthand, Longhand, Reassignment에 대해서 예시 코드를 통해 보도록 하겠다.

추가적으로 필요하다고 생각되는 tensor operation에 대해서는 하단의 내용을 추가할 예정이다.

Pytorch의 Tensor 연산 document : https://docs.pytorch.org/docs/stable/torch.html

참고자료 : https://www.youtube.com/watch?v=Ta3z9vZaoMc&list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1&index=4

---

### 0) tensor 생성 함수 정리

| 자료형(category) | dtype | 설명 | 대표 생성 함수 | dtype 지정 예시 |
|------------------|--------|--------|---------------------|-----------------------|
| **부호 없는 정수** | `torch.uint8` | Unsigned 8-bit | `torch.UInt8Tensor()` | `dtype=torch.uint8` |
| **정수** | `torch.int8` | Signed 8-bit | `torch.Int8Tensor()` | `dtype=torch.int8` |
| | `torch.int16` (`torch.short`) | 16-bit | `torch.ShortTensor()` | `dtype=torch.int16` |
| | `torch.int32` (`torch.int`) | 32-bit | `torch.IntTensor()` | `dtype=torch.int32` |
| | `torch.int64` (`torch.long`) | 64-bit (가장 많이 사용) | `torch.LongTensor()` | `dtype=torch.int64` |
| **부동소수점(Float)** | `torch.float16` (`torch.half`) | Half precision (16-bit) | `torch.HalfTensor()` | `dtype=torch.float16` |
| | `torch.float32` (`torch.float`) | Single precision (32-bit) | `torch.FloatTensor()` | `dtype=torch.float32` |
| | `torch.float64` (`torch.double`) | Double precision (64-bit) | `torch.DoubleTensor()` | `dtype=torch.float64` |
| **Boolean** | `torch.bool` | True/False | `torch.BoolTensor()` | `dtype=torch.bool` |

In [37]:
# tensor 생성

tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

### 1) Tensor addition (덧셈)

In [38]:
# tensor addition

tensor_a + tensor_b

# another way to write addition

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [39]:
# tensor addition longhead(일반적) version

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

### 2) tensor subtraction (뻴셈)

In [40]:
# subtraction

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [41]:
# subtraction function

torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

### 3) tensor multiplication (곱셈)

In [42]:
# multiplication

tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [43]:
# multiplication longhand

torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

### 4) tensor division (나눗셈)

In [44]:
# division

tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [45]:
# division longhand

torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

### 5) tensor reminder modulus (나머지 연산)

In [46]:
# reminder modulus(나머지)

tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [47]:
# remainder longhand (나머지)

torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

### 6) tensor exponents/power (지수와 제곱근) 

In [48]:
# exponents / power (제곱)

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

### 7) reassignment (기존 tensor 값 재할당)

In [52]:
# reassignment

tensor_a + tensor_b

tensor_a = tensor_a + tensor_b

tensor_a.add_(tensor_b)

tensor([26, 32, 38, 44])

### 8) 추가적인 tensor 속성들 (내적 곱셈, 원소별 곱셈, 형태 변환, cat, stack)

In [70]:
# 데이터 생성
data_1 = [[1, 3, 4], [5, 6, 7], [9, 10, 11]]
data_2 = [[11, 13, 14], [15, 16, 17], [19, 110, 111]]

# numpy array로 변환
t1 = np.array(data_1)
t2 = np.array(data_2)

# numpy array -> tensor로 변환
tensor_1 = torch.FloatTensor(t1)
tensor_2 = torch.FloatTensor(t2)

In [79]:
# tensor의 세부 속성 (mean, sum, max, argmax)

print(tensor_2.mean()) #tensor 원소의 전체값 평균
print(tensor_2.sum()) #tensor 원소의 전체값의 합 (dim=0)을 달면 차원제거 가능
print(tensor_2.max()) #tensor 원소 중 가장 큰 값 (dim=0)을 달면 차원제거 가능
print(tensor_2.argmax()) #tensor의 모든 원소 중 가장 큰 값의 index 출력 (dim=0)을 탈면 차원제거 가능

tensor(36.2222)
tensor(326.)
tensor(111.)
tensor(8)


In [81]:
# tensor의 내적 곱셈 및 원소별 곱셈

result1 = tensor_1.matmul(tensor_2)
result2 = tensor_1.mul(tensor_2)

print(f"Matrix Multiplication result : \n{result1}\n")
print(f"element-wise Multiplication : \n{result2}\n")

Matrix Multiplication result : 
tensor([[ 132.,  501.,  509.],
        [ 278.,  931.,  949.],
        [ 458., 1487., 1517.]])

element-wise Multiplication : 
tensor([[  11.,   39.,   56.],
        [  75.,   96.,  119.],
        [ 171., 1100., 1221.]])



In [102]:
# tensor의 형태 변형 및 변환 (view(), squeeze(), unsqueeze())

reshape_tensor = tensor_1.view([3, 3]) #tensor의 형태 변경(numpy의 reshape 기능)
print(reshape_tensor)

reshape_tensor.squeeze(1) #tensor의 차원을 제거
print(reshape_tensor)

reshape_tensor.unsqueeze(dim=1) #tensor의 차원을 특정 위치에 차원을 추가함

tensor([[ 1.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 9., 10., 11.]])
tensor([[ 1.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 9., 10., 11.]])


tensor([[[ 1.,  3.,  4.]],

        [[ 5.,  6.,  7.]],

        [[ 9., 10., 11.]]])

In [108]:
# tensor 병합(cat()), 연결(stack())

new_tensor = torch.cat([tensor_1, tensor_2], dim=0) #tensor 병합하여 하나의 tensor 생성
new_stack_tensor = torch.stack([tensor_1, tensor_2], dim=0) #tensor를 연결 - 병합하지 않고 연결만 진행함

print(new_tensor)
print(new_stack_tensor)

tensor([[  1.,   3.,   4.],
        [  5.,   6.,   7.],
        [  9.,  10.,  11.],
        [ 11.,  13.,  14.],
        [ 15.,  16.,  17.],
        [ 19., 110., 111.]])
tensor([[[  1.,   3.,   4.],
         [  5.,   6.,   7.],
         [  9.,  10.,  11.]],

        [[ 11.,  13.,  14.],
         [ 15.,  16.,  17.],
         [ 19., 110., 111.]]])


# 3. Neural Network Model