# [Pytorch basic document]

-----

pytorch를 활용하여 만들 수 있는 model은 무궁무진하지만 기초를 알지 못한다면 원하는 모델을 만들기는 쉽지 않다

해당 project에서는 pytorch의 기능과 함수들에 대해서 자세하게 보고 활용하여 활용 방법에 대해서 다루는 것을 목적으로 한다.

- Python Version : Python 3.13.7

참고 자료 : https://www.youtube.com/watch?v=kY14KfZQ1TI&list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1

참고자료 : https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html

-----

## 목차(contents)

- 1. Tensor (Tensor 생성, Tensor의 Attribution)
- 2. Tensor Operations
- 3. Tensor Math
- 4. Neural Network (make, train, evaluate(using test, new data), save & load model)
- 5. CNN(Convolution Neural Network) - Image fliter, Image kernel, Convolutional Layer & RGB, Pooling Layer, Train, Test, Checking Work

In [2]:
# pytorch install, numpy

%pip install --upgrade pip
%pip install torch
%pip install --upgrade torch
%pip install numpy
%pip install --upgrade numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [4]:
# pytorch 모델 import

import torch

# 1. Tensor란 무엇인가?
---

tensor(텐서)는 array나 matrix와 유사한 특수 자료구조로, pytorch에서는 tensor를 통해 model으로의 input과 output 뿐만 아닌 모델의 매개변수를 encoding하는 과정에 사용된다.

tensor는 numpy의 ndarray와 유사하지만, GPU나 연산 가속을 위한 특수 하드웨어에서 실행 가능하다는 점이 다르다.

---

### Tensor의 종류

|Dimension|tensor 종류|명칭|
|:---:|:---:|:---:|
|0 dimension tensor|zeroth-order-tenso|scalar|
|1 dimension tensor|First-order-tensor|vector|
|2 dimension tensor|Second-order-tensor|matrix|
|3 dimension tensor|Third-order-tensor|tensor|
|4 dimension tensor|Fourth-order-tensor|stack with 3 dimension tensor|
|5 dimension tensor|Fifth-order-tensor|expand side with 4 dimension tensor|
|...|...|...|

참고자료 : https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html

참고자료 : https://www.youtube.com/watch?v=2yBEZzQu8dA&list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1&index=2



## 1) Tensor 초기화
---

tensor 생성 당시 자료형은 자동으로 유추하여 맞게 생성되기 때문에 따로 지정할 필요는 없다.

크게 tensor의 생성 방법으로는 4가지로 나뉜다.

1) data -> tensor
2) data -> numpy array -> tensor
3) original_tensor -> duplicate_tensor(attribute 유지 O)
4) original_tensor -> duplicate_tensor(attribute 유지 X)
5) data(zero, one, random) -> tensor

---

In [ ]:
# tensor 생성 (data -> tensor)

data = [[1, 2],[3, 4]] # 데이터 배열 생성
x_data = torch.tensor(data) # data를 tensor로 변환

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [7]:
# tensor 생성 (data -> numpy array -> tensor)
import numpy as np

np_array = np.array(data) # numpy array 생성
x_np = torch.from_numpy(np_array) # numpy array -> tensor로 변환

print(x_np)

tensor([[1, 2],
        [3, 4]])


In [10]:
# tensor 생성 (다른 tensor -> 새로운 tensor)
# 속성의 유지여부에 따라 ones_like, rand_like를 나눠서 쓰는데 속성에는 tensor의 shape과 datatype이 해당된다.

tensor_ones = torch.ones_like(x_data) # 기존 tensor의 속성을 유지
tensor_rand = torch.rand_like(x_data, dtype=float) # 기존 tensor의 속성을 변경

print(f"Ones Tensor : \n {tensor_ones} \n")
print(f"Random Tensor : \n {tensor_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.2812, 0.3116],
        [0.9550, 0.9348]], dtype=torch.float64) 



In [14]:
# tensor 생성을 random(랜덤값) 또는 constant(상수값)을 활용하여 생성하는 방법

shape = (3, 5) #tensor의 차원을 column:3, row:5로 setting

rand_tensor = torch.rand(shape) #랜덤값으로 shape에 맞게 tensor를 생성
ones_tensor = torch.ones(shape) #모든 원소값은 1로 shape에 맞게 tensor 생성
zeros_tensor = torch.zeros(shape) #모든 원소값을 0으로 shape에 맞게 tensor 생성

# 각 tensor의 구조 및 원소의 상태를 print하여 확인
print(f"rand_tensor \n {rand_tensor} \n")
print(f"ones_tensor \n {ones_tensor} \n")
print(f"zeros_tensor \n {zeros_tensor} \n")

rand_tensor 
 tensor([[0.5021, 0.9660, 0.7524, 0.6395, 0.1106],
        [0.5917, 0.0515, 0.1206, 0.4332, 0.5482],
        [0.5613, 0.7968, 0.8140, 0.0054, 0.6530]]) 

ones_tensor 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

zeros_tensor 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 



## 2) Tensor의 Attribute(속성)

---

tensor의 attribute(속성)은 tensor의 shape, datatype 및 store device location을 의미한다.

따라서, 각 tensor는 이런 attribute를 모두 가지고 있기 때문에 특정 tensor의 shape/dtype/device의 속성을 확인이 가능하다

---

In [19]:
# tensor 랜덤값으로 생성

tensor_sample = torch.rand(2, 3) #랜덤 값을 활용하여 생성한 2x3 tensor

print(f"tensor_sample \n {tensor_sample} \n") #tensor_sample을 출력
print(f"Shape of tensor : {tensor_sample.shape}") #tensor_sample의 shape을 출력
print(f"Datatype of tensor : {tensor_sample.dtype}") #tensor_sample의 데이터 타입을 출력
print(f"Device tensor is stored on : {tensor_sample.device}") #tensor_sample이 저장된 device의 location을 출력

tensor_sample 
 tensor([[0.9423, 0.5867, 0.9045],
        [0.5297, 0.6923, 0.8298]]) 

Shape of tensor : torch.Size([2, 3])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


## 3) Tensor Operation(텐서 연산)

---

선형대수 연산 기능, 수학적 계산, 인덱싱, 슬라이싱, 임의 샘플링 등 tensor 구조로 연산 기능을 지원하는 pytorch에는 다양한 함수가 존재한다.

가장 기본적인 Reshape, Slice 기법을 확인 후 수학적 tensor 연산인 Add, Subtract, Multiply, Divide, Remainders, Exponent, Shorthand, Longhand, Reassignment에 대해서 예시 코드를 통해 보도록 하겠다.

추가적으로 필요하다고 생각되는 tensor operation에 대해서는 하단의 내용을 추가할 예정이다.

Pytorch의 Tensor 연산 document : https://docs.pytorch.org/docs/stable/torch.html

참고자료 : https://www.youtube.com/watch?v=Ta3z9vZaoMc&list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1&index=4

---